apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lovable-clone-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"