apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lovable-clone-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"