apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lovable-clone-staging
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            memory: "384Mi"
            cpu: "200m"
          limits:
            memory: "768Mi"
            cpu: "400m"