apiVersion: v1
kind: ConfigMap
metadata:
  name: lovable-config
  namespace: lovable-clone-staging
data:
  NODE_ENV: "staging"
  DATABASE_URL: "postgresql://postgres:password@postgres-service:5432/lovable_clone_staging"
  REDIS_URL: "redis://redis-service:6379"
  PORT: "3000"
  LOG_LEVEL: "info"