apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lovable-clone

resources:
- ../../namespace.yaml
- ../../configmap.yaml
- ../../postgres-deployment.yaml
- ../../redis-deployment.yaml
- ../../backend-deployment.yaml
- ../../frontend-deployment.yaml

images:
- name: lovable-clone/backend
  newTag: latest
- name: lovable-clone/frontend
  newTag: latest